services:
  postgres:
    image: postgres:15
    container_name: votify-database
    restart: always
    environment:
      POSTGRES_DB: votifydb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
