spring:
  application:
    name: votify-service
  datasource:
    url: jdbc:postgresql://localhost:5432/votifydb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    contexts: prod

