spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/votifydb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: dev
